version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reinvent2020"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1h87t6zrie6kb"
s3_prefix = "reinvent2020"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
